services:
  api-gateway:
    container_name: api-gateway
    image: tobyawo/api-gateway
    build: ./
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888/config-server
      - spring.config.import=optional:configserver:http://config-server:8888/config-server
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://localhost:5044"  # Replace `logstash` with the actual hostname of your Logstash container
        tag: "api-gateway"                  # Optional: adds a tag to help identify logs in Logstash
networks:
  default:
    external:
      name: gm-services-docker-network
#Network: Make sure the network gm-services-docker-network is created and available:
#docker network create g4m-services-docker-network