services:
  discovery-server:
    container_name: discovery-server
    image: tobyawo/discovery-server
    build: ./
    restart: on-failure
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888/config-server
      - spring.config.import=optional:configserver:http://config-server:8888/config-server
    ports:
      - "8761:8761"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"    # Replace with Fluentd service hostname if different
        tag: "discovery-server"              # Optional: adds a tag to help identify logs in Fluentd output


networks:
  default:
    external:
      name: gm-services-docker-network
#Network: Make sure the network gm-services-docker-network is created and available:
#docker network create g4m-services-docker-network