services:
  account-api:
    container_name: account-api
    image: tobyawo/account-api
    build: .
    restart: on-failure
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888/config-server
      - spring.config.import=optional:configserver:http://config-server:8888/config-server
    ports:
      - "4002:4002"
    depends_on:
      - config-server
      - discovery-server
      - mongodb
    networks:
      - gm-services-docker-network
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        tag: "account-api"

  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - gm-services-docker-network

  api-gateway:
    container_name: api-gateway
    image: tobyawo/api-gateway
    build: .
    restart: on-failure
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888/config-server
      - spring.config.import=optional:configserver:http://config-server:8888/config-server
    ports:
      - "8080:8080"
    depends_on:
      - config-server
      - discovery-server
    networks:
      - gm-services-docker-network
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        tag: "api-gateway"

  asset-management-api:
    container_name: asset-management-api
    image: tobyawo/asset-management-api
    build: .
    restart: on-failure
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888/config-server
      - spring.config.import=optional:configserver:http://config-server:8888/config-server
    ports:
      - "4001:4001"
    depends_on:
      - config-server
      - discovery-server
    networks:
      - gm-services-docker-network
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        tag: "asset-management-api"

  config-server:
    container_name: config-server
    image: tobyawo/config-server
    build: .
    restart: on-failure
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - gm-services-docker-network
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        tag: "config-server"

  discovery-server:
    container_name: discovery-server
    image: tobyawo/discovery-server
    build: .
    restart: on-failure
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888/config-server
      - spring.config.import=optional:configserver:http://config-server:8888/config-server
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    networks:
      - gm-services-docker-network
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        tag: "discovery-server"

  notification-api:
    container_name: notification-api
    image: tobyawo/notification-api
    build: .
    restart: on-failure
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888/config-server
      - spring.config.import=optional:configserver:http://config-server:8888/config-server
    ports:
      - "8099:8099"
    depends_on:
      - config-server
      - discovery-server
    networks:
      - gm-services-docker-network
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        tag: "notification-api"

  transaction-api:
    container_name: transaction-api
    image: tobyawo/transaction-api
    build: .
    restart: on-failure
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888/config-server
      - spring.config.import=optional:configserver:http://config-server:8888/config-server
    depends_on:
      - config-server
      - discovery-server
    networks:
      - gm-services-docker-network
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        tag: "transaction-api"

networks:
  gm-services-docker-network:
    driver: bridge
