services:
  config-server:
    container_name: config-server
    image: tobyawo/config-server
    build: ./
    restart: on-failure
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://localhost:5044"  # Replace `logstash` with the actual hostname of your Logstash container
        tag: "config-server"                # Optional: adds a tag to help identify logs in Fluentd output
    networks:
      - default

networks:
  default:
    external:
      name: gm-services-docker-network
#Network: Make sure the network gm-services-docker-network is created and available:
#docker network create g4m-services-docker-network