services:
  asset-management-api:
    container_name: asset-management-api
    image: tobyawo/asset-management-api
    build: ./
    restart: on-failure
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888/config-server
      - spring.config.import=optional:configserver:http://config-server:8888/config-server
    ports:
      - "4001:4001"
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://localhost:5044"  # Replace `logstash` with the actual hostname of your Logstash container
        tag: "asset-management-api"               # Optional: adds a tag to help identify logs in Fluentd output


networks:
  default:
    external:
      name: gm-services-docker-network
#Network: Make sure the network gm-services-docker-network is created and available:
#docker network create g4m-services-docker-network