apiVersion: v1
kind: Service
metadata:
  name: discovery-server-service
spec:
  type: NodePort  # Change from ClusterIP to NodePort
  selector:
    app: discovery-server-service
  ports:
    - protocol: TCP
      port: 8761         # The service port inside the cluster
      targetPort: 8086    # The port inside the container
      nodePort: 30008    # The port exposed on each node for external access
