apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-transaction-api-config
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/fluentd-transaction-api/*.log
      pos_file /fluentd/log/fluentd-asset-management-api.pos
      tag fluentd-asset-management-api.log
      <parse>
        @type none
      </parse>
    </source>

    <match fluentd-asset-management-api.log>
      @type stdout  # Replace this with your preferred output plugin
      @log_level info
    </match>


#Create this config on node using
#  kubectl apply -f fluentd-gm-user-config.yaml
#  The Fluentd sidecar reads the logs from /var/log/gm-access,
#  filters them as needed, and forwards them to an aggregator Fluentd node or directly to Kafka.
