apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-api-deployment
  labels:
    app: transaction-api-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-api-service
  template:
    metadata:
      labels:
        app: transaction-api-service
    spec:
      containers:
        # Main Application Container
        - name: transaction-api
          image: tobyawo/transaction-api
          ports:
            - containerPort: 4000
          volumeMounts:
            - name: log-volume
              mountPath: /var/log/transaction-api  # Path where logs are written by the application

        # Fluentd Sidecar Container
        - name: fluentd-sidecar
          image: fluentd
          ports:
            - containerPort: 24224  # Fluentd listening port for forwarding logs
          volumeMounts:
            - name: log-volume
              mountPath: /var/log/transaction-api  # Shared volume for reading logs
            - name: fluentd-config
              mountPath: /fluentd/etc  # Fluentd configuration directory
          command: ["fluentd", "-c", "/fluentd/etc/fluent.conf"]
          resources:
            limits:
              memory: "200Mi"
              cpu: "100m"

      # Volumes for Shared Log Storage and ConfigMap
      volumes:
        - name: log-volume
          emptyDir: {}  # Shared volume for logs between containers
        - name: fluentd-config
          configMap:
            name: fluentd-transaction-api-config  # ConfigMap containing Fluentd configuration
