apiVersion: v1
kind: Service
metadata:
  name: transaction-api
spec:
  type: NodePort  # Change from ClusterIP to NodePort
  selector:
    app: transaction-api
  ports:
    - protocol: TCP
      port: 4000         # The service port inside the cluster
      targetPort: 4000    # The port inside the container
      nodePort: 30003      # The port exposed on each node for external access
