apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-api-gateway-config
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/api-gateway/*.log  # Read logs from application log directory
      pos_file /var/log/api-gateway/fluentd.pos
      tag api-gateway.log
      format json
    </source>

    <filter api-gateway.log>
      @type grep
      <regexp>
        key level
        pattern ^(ERROR|WARN)$  # Filter logs with ERROR or WARN levels
      </regexp>
    </filter>

    <match api-gateway.log>
      @type forward
      <server>
        host kafka  # Hostname of Fluentd aggregator node
        port 9092
      </server>
    </match>


#Create this config on node using
#  kubectl apply -f fluentd-gm-user-config.yaml
#  The Fluentd sidecar reads the logs from /var/log/gm-access,
#  filters them as needed, and forwards them to an aggregator Fluentd node or directly to Kafka.
