apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  type: NodePort  # Change from ClusterIP to NodePort
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 8080         # The service port inside the cluster
      targetPort: 8080    # The port inside the container
      nodePort: 30000      # The port exposed on each node for external access
